apiVersion: v1
kind: Service
metadata:
  name: tti301-logs-service
spec:
  type: NodePort
  selector:
    app: tti301-logs
  ports:
    - name: tti301-logs
      protocol: TCP
      port: 8000
      targetPort: 8000