apiVersion: v1
kind: Service
metadata:
  name: tti301-observacoes-service
spec:
  type: NodePort
  selector:
    app: tti301-observacoes
  ports:
    - name: tti301-observacoes
      protocol: TCP
      port: 5000
      targetPort: 5000